Check if window.chrome property is present on Chrome and Opera
antibot-dev-team/antibot-backend pull request #8
Opened 2021-08-11 10:56 UTC by Cravtos

> window.chrome is an object that seems to provide features to Chrome extension developers. While it is available in vanilla mode, it’s not available in headless mode.

This branch is based on [fix-firefox](https://github.com/antibot-dev-team/antibot-backend/pull/7) because for this check user agent should be accessible to analyzer, and on [fix-firefox](https://github.com/antibot-dev-team/antibot-backend/pull/7) it is.

2021-08-12 05:08 UTC, manmolecular requested changes
Однострочные импорты лучше делать в одну строку, не:
```go
import (
	"strings"
)
```
а:
```go
import "strings"
```

2021-08-12 05:08 UTC, manmolecular commented on antibot/analyzer/analyzer.go
> +	isChromeOrOpera = isChromeOrOpera || strings.Contains(ua, "Opera") || strings.Contains(ua, "OPR")
Я бы и здесь сделал проверку в LowerCase, если вдруг UA будет как-то меняться и т.д., чтобы расширить совместимость

2021-08-12 16:33 UTC, Cravtos commented on antibot/analyzer/analyzer.go
> +	isChromeOrOpera = isChromeOrOpera || strings.Contains(ua, "Opera") || strings.Contains(ua, "OPR")
Готово -- dc9ef82

2021-08-13 05:05 UTC, manmolecular approved these changes

2021-08-13 08:52 UTC, merged